import pygame
import random

# Constants
WIDTH, HEIGHT = 800, 600
FLY_SIZE = 30
MIN_SHELF_WIDTH = 100
MAX_SHELF_WIDTH = 400
SHELF_HEIGHT = 100
HAND_WIDTH = 100
HAND_HEIGHT = 20
OBSTACLE_SPEED = 3
POWERUP_SPEED = 3
SPIDERWEB_SPEED = 3
GAP_BETWEEN_SHELVES = 150
GAP_BETWEEN_ROWS = 300

# Initialize Pygame
pygame.init()

